platform:
- x64
environment:
  nodejs_version: "6"
cache:
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'
- node_modules
branches:
  only:
  - release
  - /^v\d+\.\d+\.\d+/
install:
- ps: Install-Product node $env:nodejs_version $env:platform
- set PATH=%APPDATA%\npm;%PATH%
- npm install
- npm update

test_script:
- node --version
- npm --version
- npm run lint

build_script:
- npm run publish
