language: node_js
node_js: "6"
os:
- osx
- linux
dist: trusty
osx_image: xcode8.3
sudo: false

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm

branches:
  only:
  - release
  - /^v\d+\.\d+\.\d+/

install:
- npm install
- npm update

script:
- npm run lint
- npm run publish
