language: node_js
node_js: "6"
os:
- osx
- linux
dist: trusty
osx_image: xcode8.3
sudo: false

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm

branches:
  only:
  - release
  - /^v\d+\.\d+\.\d+/

install:
- npm install
- npm update

script:
- npm run lint
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    echo "Starting Certificate installation";
    export CERTIFICATE_P12=Certificate.p12;
    echo $CERTIFICATE_OSX_P12 | base64 --decode > $CERTIFICATE_P12;
    export KEYCHAIN=build.keychain;
    security create-keychain -p $CERTIFICATE_PASSWORD $KEYCHAIN;
    security default-keychain -s $KEYCHAIN;
    security unlock-keychain -p $CERTIFICATE_PASSWORD $KEYCHAIN;
    security import $CERTIFICATE_P12 -k $KEYCHAIN -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign;
    security set-key-partition-list -S apple-tool:,apple: -s -k $CERTIFICATE_PASSWORD $KEYCHAIN
  fi
- npm run publish
